apiVersion: v1
kind: Service
metadata:
  name: squash-restful-api
  labels:
    app: squash
spec:
  selector:
    app: squash
    tier: api
  ports:
    - name: https
      protocol: TCP
      port: 443
    - name: http
      protocol: TCP
      port: 80
  type: LoadBalancer
